import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import centersRouter from "./centers";
import roomsRouter from "./rooms";
import childrenRouter from "./children";
import attendanceRouter from "./attendance";
import contactsRouter from "./contacts";
import dashboardRouter from "./dashboard";
import { checkInRouter } from "./check-in";
import { childDocsRouter } from "./child-docs";
import { childAuthorizationsRouter } from "./child-authorizations";
import reportsRouter from "./reports";
import servicesRouter from "./services";
import providersRouter from "./providers";
import casesRouter from "./cases";
import importCases2026Router from "./import-cases-2026";
import calendarioRouter from "./calendario";
import planificacionesRouter from "./planificaciones";
import adminSyncRouter from "./admin-sync";
import followupReportsRouter from "./followup-reports";
import aiRouter from "./ai";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(centersRouter);
router.use(roomsRouter);
router.use(childrenRouter);
router.use(attendanceRouter);
router.use(contactsRouter);
router.use(dashboardRouter);
router.use("/check-in", checkInRouter);
router.use("/child-docs", childDocsRouter);
router.use("/child-authorizations", childAuthorizationsRouter);
router.use(reportsRouter);
router.use(servicesRouter);
router.use(providersRouter);
router.use(casesRouter);
router.use(importCases2026Router);
router.use(calendarioRouter);
router.use(planificacionesRouter);
router.use("/admin-sync", adminSyncRouter);
router.use(followupReportsRouter);
router.use(aiRouter);

export default router;
